### ISSUE TITLE
Taro2.x还是Taro3.x

### ISSUE THREAD

**Issue by zhuying412** [b2nil/taro-ui-vue3#106]
#### 问题描述 
请问该项目的构建是基于Taro2.X还是Taro3.X？

#### 版本信息
taro-ui-vue3@1.0.0-alpha.21

#### 涉及的平台
weapp，h5

**Comment by b2nil** [comment]
Taro 2.X 支持用 Vue 写？

**Comment by zhuying412** [comment]
Taro 2.X是不支持用VUE写，可万一你们牛B又套了一层呢？问问还是保险的。
