### ISSUE TITLE
imagepicker @image-pick=H5图片点击放大效果不生效

### ISSUE THREAD

**Issue by 1014470807** [b2nil/taro-ui-vue3#107]
imagepicker @image-pick=H5图片点击放大效果不生效

**Comment by b2nil** [comment]
最好贴一下代码，并告知使用的版本。
另外，是 `@image-pick` 事件没生效，还是 `点击放大效果` 不生效？后者是需要自己实现的。

**Comment by b2nil** [comment]
先关闭了！
