### ISSUE TITLE
希望VirtualScroll增加一个列表数据为空的时候显示的结构

### ISSUE THREAD

**Issue by wzs28150** [b2nil/taro-ui-vue3#112]
#### 问题描述 

当我在使用VirtualScroll 搭配search搜索的时候 ，有时候搜不到内容下面列表就显示的空白，希望可以添加empty时的结构
或者提供一个empty的插槽也好
![image](https://user-images.githubusercontent.com/21290257/125258099-99035580-e330-11eb-9e07-6ffe1af911f9.png)

**Comment by b2nil** [comment]
正好在处理这个组件的尺寸适配问题，这个问题可以一并解决。

**Comment by b2nil** [comment]
@wzs28150 

现有的 footer 插槽能不能满足你的使用场景?
