### ISSUE TITLE
PickerView Demo 不能正常选择日期

### ISSUE THREAD

**Issue by b2nil** [b2nil/taro-ui-vue3#20]
PickerViewColumn 滑动后不能固定在选择的位置上，而是又回到了顶部。

**Comment by b2nil** [comment]
Fixed by Taro in https://github.com/NervJS/taro/issues/7638

**Comment by liuyunzyj** [comment]
"@tarojs/taro": "3.0.17", PickerView Demo（react） 无法显示https://nervjs.github.io/taro/docs/components/forms/picker-view/

**Comment by b2nil** [comment]
@liuyunzyj react 版本的 taro ui，你要到 taro ui 的官方 repo 去提 issue。
