### ISSUE TITLE
Action-Sheet 展示页面出现关于 default slot 的警告

### ISSUE THREAD

**Issue by b2nil** [b2nil/taro-ui-vue3#3]
开发工具所报的警告信息如下：
```
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
```

原因是组件插槽所插入的是插槽内容，而非函数值。Vue3 推荐使用函数式插槽，以便获得更佳的性能。
```
h(AtActionSheetHeader, null, props.title) // 不推荐的写法
```

正确的写法如下：
```
h(AtActionSheetHeader, null, { default: () => props.title })

```

**Comment by wmdsj-z** [comment]
![image](https://user-images.githubusercontent.com/65765396/118952161-493a8a80-b98e-11eb-9ef0-d92630d54492.png)
函数也会有警告是啥鬼

**Comment by b2nil** [comment]
@wmdsj-z 

ElTable 的子节点也需要传入函数式插槽，直接传数组是会报警告信息的。
```ts
createVNode(ElTable, {}, { default: () => [
  createVNode(ElTableColumn, {}),
  ...
]})
```

**Comment by LBJDJW** [comment]
谢谢！

**Comment by LBJDJW** [comment]
我今天看到你的问题 解决了 我也遇到了 报了警告 Non-function value encountered for default slot. Prefer function slots for better performance

**Comment by ocweai** [comment]
[Vue warn]: Slot "columns" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 

v-slots={{ columns: () => slots.tableColumns() }}
我应该肿么使用？

**Comment by b2nil** [comment]
@Minitiai 
使用 jsx 的话，遵照 [`@vue/jsx-next`](https://github.com/vuejs/jsx-next#slot) 的语法来用。
从错误信息来看，你应该将代码放到 render 函数里面。
```ts
// 在 setup 中返回 render 函数
setup(props, { slots }) {
  ...
  return () => {
     return (/* jsx 代码 */)
  }
}

// 或直接使用 render
render() {
  return (/* jsx 代码 */)
}

```
