### ISSUE TITLE
希望加个下拉刷新加载更多组件

### ISSUE THREAD

**Issue by JakeWoki** [b2nil/taro-ui-vue3#34]

**Comment by b2nil** [comment]
是`下拉刷新`加载？ 还是`到达底部`之后`上拉加载`？

**Comment by JakeWoki** [comment]
下拉刷新+上拉加载更多

**Comment by b2nil** [comment]
Taro 官方有一个 `VirtualList` 组件，应该能满足你这个需求。
Vue 2.0 是直接可以用的，但是基于 Vue 3.0 的 `VirtualList` 需要另外实现，目前还不知道具体什么时间能用。

Taro 官方单独实现的话，这个项目就没必要实现了。

如果他们需要很久，欢迎 PR。

**Comment by JakeWoki** [comment]
VirtualList文档没找到>_<

**Comment by JakeWoki** [comment]
https://taro-docs.jd.com/taro/docs/virtual-list
这个？

**Comment by b2nil** [comment]
是的，vue 2.0 能用的

**Comment by JakeWoki** [comment]
VirtualList没有下拉刷新

**Comment by b2nil** [comment]
`下拉刷新` 应该可以用 `onPullDownRefresh` 直接刷新数据

**Comment by b2nil** [comment]
> VirtualList没有下拉刷新。[taro-listview](https://github.com/Rahim-Chan/taro-listview)，其实我想弄一个这样完整的组件，不过我对vue、js都不熟悉

这个项目 [taro-listview](https://github.com/Rahim-Chan/taro-listview) 也是使用 `onPullDownRefresh` 来实现下拉刷新的，Taro 有封装了这些方法。

| 事件名称 | 说明 | 类型 | 默认值 | 必传
| -- | -- | -- | -- | --
| onPullDownRefresh | 下拉刷新触发函数 | function | - | -
| onScrollToLower | 上拉底触发函数 | function | - | -

```ts
onPullDownRefresh = () => {
  getData();
};

onScrollToLower = async fn => {
  await getData();
  fn();
};
```

如果想自己写一个完整的组件的话，就写一个基于 vue 3.0 的 `VirtualList` 吧

**Comment by b2nil** [comment]
已在 #42 中新增了虚拟列表组件，升级至 `v1.0.0-alpha.10` 即可使用。
