### ISSUE TITLE
引入之后整个项目打包多了近300k

### ISSUE THREAD

**Issue by pecopeco** [b2nil/taro-ui-vue3#57]
作为小程序项目，这个大小有点接受不了

**Comment by b2nil** [comment]
是的，目前是比较大。有什么好的优化建议么？

**Comment by whyour** [comment]
可以先按组件打包，再打个整包

**Comment by b2nil** [comment]
@whyour 
类似 [element-plus](https://github.com/element-plus/element-plus) 的做法么？

**Comment by whyour** [comment]
> @whyour
> 类似 [element-plus](https://github.com/element-plus/element-plus) 的做法么？

对，多包管理 lerna

**Comment by b2nil** [comment]
关于这个问题，可从 `taro-ui-vue3/lib` 下按需引入组件。
之前版本的 `taro-ui-vue3/lib` 存在引用路径问题（#63），在 `taro-ui-vue3@1.0.0-alpha.16` 已修复。
