### ISSUE TITLE
v1.0.0-dev.1 - Can't resolve '@/style/components/skeleton.scss'

### ISSUE THREAD

**Issue by b2nil** [b2nil/taro-ui-vue3#59]
#### 问题描述 
`v1.0.0-dev.1` 仅用于测试 skeleton 组件。
目前样式引入存在问题。

#### 版本信息
`v1.0.0-dev.1`

#### 涉及的平台
小程序, h5

#### 错误信息

```bash
./node_modules/taro-ui-vue3/dist/index.esm.js   or index.umd/js
Module not found: Can't resolve '@/style/components/skeleton.scss' in 'E:\miniprogram\test\node_modules\taro-ui-vue3\dist'
```

#### 临时解决方案
请使用 `v1.0.0-alpha.13`

**Comment by bokuns** [comment]
我也遇到一样的问题，只要 `import { AtTabBar } from 'taro-ui-vue3` 就会报这个错。

**Comment by liov** [comment]
> #### 临时解决方案
> 请使用 `v1.0.0-alpha.13`

does not contain an export named 'View'

**Comment by b2nil** [comment]
@liov
目前 编译到  h5 需额外配置一下脚本和 wepack，具体步骤看看 Readme 关于 h5 的说明。

**Comment by b2nil** [comment]
fixed in alpha.14
