### ISSUE TITLE
虚拟列表无法像手风琴一样直接在列表里显示详情吗

### ISSUE THREAD

**Issue by liov** [b2nil/taro-ui-vue3#70]
#### 问题描述 

直接加个手风琴组件会破坏整体样式
#### 版本信息

v1.0.0-alpha.8
#### 涉及的平台

h5
#### 错误信息

```bash
// error message here


```
#### 代码

```ts
// code here

```

**Comment by b2nil** [comment]
可以显示啊，default slot 的内容可以自定义，但是目前虚拟列表的单项高度只支持固定高度。

**Comment by liov** [comment]
> 可以显示啊，default slot 的内容可以自定义，但是目前虚拟列表的单项高度只支持固定高度。

就是固定高度影响的，以后会支持自适应吗

**Comment by b2nil** [comment]
后面会支持可变高度，但具体时间不能确定。

**Comment by b2nil** [comment]
先关闭了，后续有问题再开新 issue
