### ISSUE TITLE
模拟态框框 样式问题

### ISSUE THREAD

**Issue by zeng-pro** [b2nil/taro-ui-vue3#76]
模拟态框框 样式问题
https://b2nil.github.io/taro-ui-vue3-demo/#/action/modal
<img width="500" alt="企业微信截图_598fb2c5-fb2a-4a2d-b961-52fe122751ea" src="https://user-images.githubusercontent.com/22758452/106692075-33879c00-660f-11eb-9bd5-32f70c323032.png">

**Comment by b2nil** [comment]
这是 Taro 转 H5 时，官方内置的 component 样式导致的问题，
两个 button 放在一起时，后面的一个设置了 `margin-top` 。

下个版本手动改一下 H5 样式
