### ISSUE TITLE
AtToast 的 isOpened 一开始为true时，报TypeError: Cannot set property '_timer' of undefined和TypeError: Cannot read property '_isOpened' of undefined错

### ISSUE THREAD

**Issue by domsgit** [b2nil/taro-ui-vue3#80]
#### 问题描述 

进入页面请求接口，先需要设置 AtToast 为 loading 的状态，但是 当设置 isOpened 为true时，组件报错。
#### 版本信息

v1.0.0-alpha.17
#### 涉及的平台

weapp
#### 错误信息

```bash
// error message here
TypeError: Cannot set property '_timer' of undefined
TypeError: Cannot read property '_isOpened' of undefined
```
#### 代码

```ts
// code here
<template>
  <AtToast :isOpened="true" :text="'正在加载中'" :status="'loading'"></AtToast>
</template>

<script setup lang="ts">
import { AtToast } from 'taro-ui-vue3'
</script>

```

**Comment by domsgit** [comment]
补充：克隆下该仓库的源码后试了一下没问题。就是使用编译后发布的版本的taro-ui-vue3就会有这个报错。

**Comment by b2nil** [comment]
@domsgit 
这个问题已经修复了(e3c3dc43f66e1332c042c81ab9774d0447b79736)，但是好像忘记了发新版，抱歉。
今天晚上发一个新的版本。

**Comment by domsgit** [comment]
> @domsgit
> 这个问题已经修复了([e3c3dc4](https://github.com/b2nil/taro-ui-vue3/commit/e3c3dc43f66e1332c042c81ab9774d0447b79736))，但是好像忘记了发新版，抱歉。
> 今天晚上发一个新的版本。

直接用下面的方式替代也没有这个问题了。而且不用在`template`中添加代码。

`
  Taro.showToast({
    title: `加载数据中...`,
    icon: 'loading',
    duration: 0
  })
`
