### ISSUE TITLE
at-input 组件 当type为digit，值默认为0时，输入框后面会出现0

### ISSUE THREAD

**Issue by domsgit** [b2nil/taro-ui-vue3#81]
#### 问题描述 

at-input 组件 当type为digit，值默认为0时，输入框后面会出现0
#### 版本信息

1.0.0-alpha.17
#### 涉及的平台

weapp
#### 错误信息

```bash
// error message here
//样式错误

```
#### 代码

```ts
// code here
<at-input
  style="text-align:right"
  clear
  name="value"
  title="标题"
  type="digit"
  placeholder="请输入"
  :value="0"
/>
```

**Comment by domsgit** [comment]
补充： 当value为Number的0时会如此。但是当value值为String的'0'时正常。

**Comment by b2nil** [comment]
`h5` 还是小程序？
快速跑了以下 `h5` 的 demo，没有发现这种情况。

**Comment by b2nil** [comment]
fixed in e4d840fd3fe69e6b8ee3879ba0bf39d80ce98871
