### ISSUE TITLE
at-search-bar组件的onClear事件无效

### ISSUE THREAD

**Issue by angeltxwh** [b2nil/taro-ui-vue3#88]
#### 问题描述 
点击clear按钮无法触发handleClear方法，并且我看文档说不传onClear方法也会清空搜索文本，但是实际测试无论传不传onClear方法都不会清空搜索文本

#### 版本信息
^1.0.0-alpha.18

#### 涉及的平台
weapp(目前只测试了微信平台)

#### 错误信息
-
#### 代码
```
<at-search-bar v-model:value="searchValue" @clear="handleClear" />

handleClear() {
this.searchValue = "";
}
```

**Comment by b2nil** [comment]
先看看你的 vue 和 @vue/compiler-sfc 的版本，如果高于 3.0.5，请将版本固定在 3.0.5 再试一下。

**Comment by angeltxwh** [comment]
VUE版本3.0.0

**Comment by angeltxwh** [comment]
尝试最新版3.0.7和大佬推荐版本3.0.5后发现：

307版本问题依旧，305版本问题改善

另外想请教下大佬这具体是什么原因呢？

**Comment by b2nil** [comment]
这是 vue@3.0.6 中引入的一个 commit 导致的问题，详情看[这个 taro issue ](https://github.com/NervJS/taro/issues/8796)。

**Comment by b2nil** [comment]
Fixed in `v1.0.0-alpha.19`.
Update to `v1.0.0-alpha.19`, and use the latest vue version as you wish.
