### ISSUE TITLE
SearchBar怎么一点击搜索那个文字就自动清空了的？

### ISSUE THREAD

**Issue by EdwinLam** [b2nil/taro-ui-vue3#90]
#### 问题描述 
大佬，SearchBar怎么一点击搜索那个文字就自动清空了的？我试旧版本vue2那个好像不清的

**Comment by b2nil** [comment]
之前有个 bug 导致搜索框内的文字无法通过 onActionClick 参数彻底清空，所以调整为在组件调用完 onActionClick 后默认清空文字。
如果有保留搜索文字的需求，下个版本可以调整，把这个操作留给开发者。

**Comment by EdwinLam** [comment]
> 之前有个 bug 导致搜索框内的文字无法通过 onActionClick 参数彻底清空，所以调整为在组件调用完 onActionClick 后默认清空文字。
> 如果有保留搜索文字的需求，下个版本可以调整，把这个操作留给开发者。

辛苦大佬了
